version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: collm-app
    container_name: collm-app
    ports:
      - "8501:8501"
      - "8081:8081"
    env_file:
      - .env
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    command: streamlit run app.py --server.address=0.0.0.0
